### ISSUE TITLE
.transfer.toBalance 这个接口，提示wrong tag

### ISSUE THREAD

**Issue by yourapis** [hpyer/node-easywechat#20]
.transfer.toBalance 这个接口，提示wrong tag
![Uploading QQ图片20220425063029.png…]()

**Comment by yourapis** [comment]
Error: wrong tag

    at Object.createSecureContext (_tls_common.js:271:19)

    at Object.connect (_tls_wrap.js:1559:48)

    at Agent.createConnection (https.js:130:22)

    at Agent.createSocket (_http_agent.js:265:26)

    at Agent.addRequest (_http_agent.js:224:10)

    at new ClientRequest (_http_client.js:296:16)

    at Object.request (https.js:314:10)

    at RedirectableRequest._performRequest (/var/user/node_modules/follow-redirects/index.js:279:24)

    at new RedirectableRequest (/var/user/node_modules/follow-redirects/index.js:61:8)

    at Object.request (/var/user/node_modules/follow-redirects/index.js:487:14)

**Comment by hpyer** [comment]
您提供的这个错误信息貌似并非本sdk的报错，麻烦提供更准确的错误信息。

同时，也建议您对照文档核对一下参数是否正确：

- 微信支付打款到零钱文档：https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2
- Easywechat相关接口文档：https://www.easywechat.com/5.x/payment/transfer.html

**Comment by yourapis** [comment]
> 您提供的这个错误信息貌似并非本sdk的报错，麻烦提供更准确的错误信息。
> 
> 同时，也建议您对照文档核对一下参数是否正确：
> 
> * 微信支付打款到零钱文档：https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2
> * Easywechat相关接口文档：https://www.easywechat.com/5.x/payment/transfer.html

我加您qq了，你通过一下，我就是按照easywechat的文档做的，参数啥都是对的，证书都没问题，因为付款等其他是正常的。

**Comment by hpyer** [comment]
经排查，此错误应该是未配置正确的API证书导致的。

微信支付的配置项 `cert_path` 需要传入 `apiclient_cert.p12` 文件的路径

详见微信支付官方文档（`API证书`小节）：https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=4_3
