### ISSUE TITLE
req 被 readStream 后，是不是就不能再被 readStream 了

### ISSUE THREAD

**Issue by fanybook** [hpyer/node-easywechat#5]
**感谢分享好用的微信库**

我用的框架，应该解析过 xml，用的这个（https://github.com/NaturalIntelligence/fastify-xml-body-parser/blob/master/index.js）

导致在 getContent() -> RawBody 时出现了报错
```js
"err":{"type":"BadRequestError","message":"request aborted","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/data/www/web/node_modules/raw-body/index.js:231:10)\n    at IncomingMessage.emit (events.js:310:20)\n    at abortIncoming (_http_server.js:532:9)\n    at socketOnEnd (_http_server.js:548:5)\n    at Socket.emit (events.js:322:22)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","code":"ECONNABORTED","expected":null,"length":null,"received":0,"status":400,"statusCode":400,"expose":true}
```

**Comment by fanybook** [comment]
终于能自动回复了，我暂时的 hack 方式是：
```js
'use strict';
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const Url = require("url");
const Utils_1 = require("../Utils");
const RawBody = require("raw-body");
class Request {
    constructor(req = null) {
        this._req = null;
        this._uri = '';
        this._method = '';
        this._headers = {};
        this._get = {};
        this._post = null;  <- 这里从 {} 改为 null
        this._content = null;
        this._contentType = '';
        this._ip = '';
        if (req) {
            this._req = req;
            this._uri = req.url;
            this._method = req.method.toUpperCase();
            this._headers = req.headers || {};
            this._contentType = this._headers['content-type'] || '';
            this._get = Url.parse(req.url, true).query;
            this._post = req.post;  <- 这里可以直接给 this._post 赋值
            // 提取请求ip
            if (Utils_1.isIp(this._headers['x-client-ip'])) {
                this._ip = this._headers['x-client-ip'];
            }
            else if (this._headers['x-forwarded-for']) {
                let ip = '';
                let items = this._headers['x-forwarded-for'].split(',');
                for (let i = 0; i < items.length; i++) {
                    if (!items[i])
                        continue;
                    ip = items[i].trim();
                    if (items[i].indexOf(':') > -1) {
                        let tmp = items[i].split(':');
                        if (tmp.length == 2) {
                            ip = tmp[0];
                        }
                    }
                    if (Utils_1.isIp(ip)) {
                        break;
                    }
                }
                this._ip = ip;
            }
            else if (Utils_1.isIp(this._headers['x-real-ip'])) {
                this._ip = this._headers['x-real-ip'];
            }
            else if (Utils_1.isIp(this._headers['x-forwarded'])) {
                this._ip = this._headers['x-forwarded'];
            }
            else if (Utils_1.isIp(this._headers['forwarded-for'])) {
                this._ip = this._headers['forwarded-for'];
            }
            else if (Utils_1.isIp(this._headers['client-ip'])) {
                this._ip = this._headers['client-ip'];
            }
        }
    }
    isValid() {
        return !!this._req;
    }
    getMethod() {
        if (!this.isValid)
            throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
        return this._method;
    }
    get(key) {
        if (!this.isValid)
            throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
        if (this._get[key])
            return this._get[key];
        return this.post(key);
    }
    post(key) {
        return __awaiter(this, void 0, void 0, function* () {
            if (!this.isValid)
                throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
            if (this._method !== 'POST')
                return null;
            if (!this._content && !this._post) { <- 增加条件  && !this._post
                yield this.getContent();
                let contentType = (this._headers['content-type'] || '').toLowerCase();
                if (contentType.indexOf('application/json') > -1) {
                    try {
                        this._post = JSON.parse(this._content.toString());
                    }
                    catch (e) { }
                }
                else if (contentType.indexOf('application/x-www-form-urlencoded') > -1) {
                    this._post = Utils_1.parseQueryString(this._content.toString());
                }
            }
            return this._post && this._post[key] ? this._post[key] : null;
        });
    }
    getContent() {
        return __awaiter(this, void 0, void 0, function* () {
            if (!this.isValid)
                throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
            if (this._method !== 'POST')
                return null;
            if (!this._content && !this._post) { <- 增加条件  && !this._post
                this._content = yield RawBody(this._req);
            } else if (this._post) { <- 这里增加一个条件分支
                this._content = JSON.stringify(this._post);
            }
            return this._content;
        });
    }
    getUri() {
        if (!this.isValid)
            throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
        return this._uri || '';
    }
    getContentType() {
        if (!this.isValid)
            throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
        return this._contentType || '';
    }
    getHeaders() {
        if (!this.isValid)
            throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
        return this._headers || {};
    }
    getClientIp() {
        if (!this.isValid)
            throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
        return this._ip;
    }
}
exports.default = Request;
;

```

**Comment by hpyer** [comment]
不建议直接修改dist目录下的文件，包重新安装或升级，修改的代码就丢失了。。
可以考虑继承`EasyWechat.Http.Request`类，重写你提到的几个方法，，实例化后再`rebind`就行，如：
```js
class MyRequest extends EasyWechat.Http.Request
{
  constructor() {
    // TODO
  }
  post() {
    // TODO
  }
  getContent() {
    // TODO
  }
}

let request = new MyRequest(ctx.req);

officialAccount.rebind('request', request);
```

另，不同的body解析工具解析后，不一定都是挂载到ctx.req.post的，所以暂不考虑将你的方法合并，我会再找找其他方法看

**Comment by fanybook** [comment]
@hpyer 嗯，我使用的是 fastify, 会在原始的 req 上又再封装一层，我是取出原始 req 直接给它增加 post 属性的

还有，打印信息，能否增加配置项来关闭，或者使用 pino
如果访问量大，这个打印是否会影响性能
```bash
NodeEasywechat2: Server response created: {
  content: 'XXXXX'
}
```

**Comment by hpyer** [comment]
这个需求也可以用`rebind`方法来实现。如：
```js
const MyLogger = () => {
  let args = arguments;
  args[0] = 'MyLogger: ' + args[0];
  console.log.apply(null, arguments);
}

officialAccount.rebind('log', MyLogger);
```

**Comment by fanybook** [comment]
@hpyer

**Comment by fanybook** [comment]
很奇怪  rebind ‘log’ 报错，而 'request' 没问题

"err":{"type":"TypeError","message":"this.app.log is not a function","stack":"TypeError: this.app.log is not a function\n    at Guard.<anonymous> (/data/www/polarcy.com/web/node_modules/node-easywechat2/dist/Core/ServerGuard.js:88:28)\n    at Generator.next (<anonymous>)\n    at fulfilled (/data/www/polarcy.com/web/node_modules/node-easywechat2/dist/Core/ServerGuard.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}

```js
// logger 使用 pino 打印到文件
  const pinoLogger = () => {
   let args = arguments
   args[0] = 'NodeEasywechat2: ' + args[0]

   //console.log(fileLogger)
   return console.log.apply(null, arguments)
  }
  officialAccount.rebind('log', pinoLogger)

  const req = new EasyWechat.Http.CustomRequest(request.raw)
  officialAccount.rebind('request', req)
```

**Comment by fanybook** [comment]
问题出在 offsetSet 么
```js
  rebind(id: string, value: any): void
  {
    this.offsetUnset(id);
    this.offsetSet(id, value);
  }

  /**
   * 解绑自定义服务模块
   * @param id 服务模块的id，如：cache、request、access_token
   * @param value 自定义服务模块的实例
   */
  offsetUnset(id: string): void
  {
    delete this[id];
  }

  /**
   * 绑定自定义服务模块
   * @param id 服务模块的id，如：cache、request、access_token
   * @param value 自定义服务模块的实例，可以传入一个闭包，闭包会接收一个指向Application的参数
   */
  offsetSet(id: string, value: any): void
  {
    if (isFunction(value)) {
      value = value(this);
    }
    this[id] = value;
  }
```

不知道 `value = value(this)` 其他地方用了么

我改成这样，仍然又很多问题，arguments 变得很多，也有问题
```js
  officialAccount.rebind('log', () => {
    return () => {
      let args = arguments
      args[0] = 'NodeEasywechat2: ' + args[0]
      return console.log.apply(null, arguments)
    }
  })
```

**Comment by fanybook** [comment]
这样才ok
```js
  officialAccount.rebind('log', () => {
    return function() {
      let args = arguments
      args[0] = 'NodeEasywechat2: ' + args[0]
      return fileLogger.info(...arguments)
    }
  })
```

**Comment by hpyer** [comment]
```js
if (isFunction(value)) {
  value = value(this);
}
```
应该是这个问题导致的，这段代码是因为有些api需要异步注入上下文，才这么处理的。

> 这样才ok
> 
> ```js
>   officialAccount.rebind('log', () => {
>     return function() {
>       let args = arguments
>       args[0] = 'NodeEasywechat2: ' + args[0]
>       return fileLogger.info(...arguments)
>     }
>   })
> ```

返回的函数不能用箭头函数，不然函数的上下文关系乱了，arguments作用域就变了

**Comment by hpyer** [comment]
> **感谢分享好用的微信库**
> 
> 我用的框架，应该解析过 xml，用的这个（[https://github.com/NaturalIntelligence/fastify-xml-body-parser/blob/master/index.js）](https://github.com/NaturalIntelligence/fastify-xml-body-parser/blob/master/index.js%EF%BC%89)
> 
> 导致在 getContent() -> RawBody 时出现了报错
> 
> ```js
> "err":{"type":"BadRequestError","message":"request aborted","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/data/www/web/node_modules/raw-body/index.js:231:10)\n    at IncomingMessage.emit (events.js:310:20)\n    at abortIncoming (_http_server.js:532:9)\n    at socketOnEnd (_http_server.js:548:5)\n    at Socket.emit (events.js:322:22)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","code":"ECONNABORTED","expected":null,"length":null,"received":0,"status":400,"statusCode":400,"expose":true}
> ```

我这边写demo测试了一下，确实是 fastify 框架读取了request数数据流后，就无法再次读取导致的。
这里提供另外一个解决思路，就是在fastify框架的 onReqeust 钩子中，复制一份原始request请求，然后传递给node-easywechat使用。

示例代码：
```js
const fastify = require('fastify')({
  logger: true
})

fastify.addHook('onRequest', function (request, reply, next) {

  const Stream = require('stream');

  // 这时request.raw还未被读取，所以先通过PassThrough复制一份请求数据为request.custom
  request.custom = new Stream.PassThrough();
  request.raw.pipe(request.custom);

  // 需要将请求的url、method、headers一并复制
  request.custom.url = request.raw.url;
  request.custom.method = request.raw.method;
  request.custom.headers = request.raw.headers;

  next();
});


// fastify的路由中
const EasyWechat = require('node-easywechat2');
let officialAccount = new EasyWechat.Factory.OfficialAccount({
  ...
});
// 这里使用request.custom作为请求数据传入即可
let req = new EasyWechat.Http.Request(request.custom);
officialAccount.rebind('request', req);
```

**Comment by fanybook** [comment]
嗯，这种写法上更简洁，单是不是更耗内存

**Comment by hpyer** [comment]
> 嗯，这种写法上更简洁，但是不是更耗内存

可以判断下请求的路由，不需要的就不复制。不过，我觉得还是简易继承 Request 类，然后重写一下相关方法比较好～

**Comment by fanybook** [comment]
@hpyer 嗯，我就是按照你之前说的，弄的

**Comment by fanybook** [comment]
> > 嗯，这种写法上更简洁，但是不是更耗内存
> 
> 可以判断下请求的路由，不需要的就不复制。不过，我觉得还是简易继承 Request 类，然后重写一下相关方法比较好～

嗯，我就是按照你之前说的，弄的

**Comment by hpyer** [comment]
@fanybook 
更新了一个2.2.2版本，Request对象增加了第二个参数～方便的话，帮忙测试一下～谢谢～
```js
// 传入第二个参数，即post的内容
// 支持 Buffer、object对象、JSON字符串、QueryString格式的POST内容字符串
let request = new EasyWechat.Http.Request(req, content);
```

**Comment by fanybook** [comment]
@hpyer 我还没试，但看了下代码，貌似有点问题，望确认一下

在传了 content 的情况下，如果它不是 buffer，那么只给 this._post 赋值了，也就是说 `!this._content` 是 true，还是会 `await this.getContent()`，`getContent()` 里还是会 `await RawBody(this._req)`

`let request = new EasyWechat.Http.Request(req, content);`

```js
  async post(key: string): Promise<any>
  {
    if (!this.isValid) throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
    if (this._method !== 'POST') return null;
    if (!this._content) {
      this._content = await this.getContent();
    }
    if (!this._post && this._content) {
      let contentType = (this._headers['content-type'] || '').toLowerCase();
      if (contentType.indexOf('application/json') > -1) {
        try {
          this._post = JSON.parse(this._content.toString());
        }
        catch (e) { }
      }
      else if (contentType.indexOf('application/x-www-form-urlencoded') > -1) {
        this._post = parseQueryString(this._content.toString());
      }

    }
    return this._post && this._post[key] ? this._post[key] : null;
  }

  async getContent(): Promise<Buffer>
  {
    if (!this.isValid) throw new Error('Please set request first. app.rebind(\'request\', new EasyWechat.Request(ctx.req));');
    if (this._method !== 'POST') return null;
    if (!this._content) {
      this._content = await RawBody(this._req);
    }
    return this._content;
  }
```

**Comment by hpyer** [comment]
@fanybook 确实有这个问题，已修复，重新发布了2.3.1版本

**Comment by fanybook** [comment]
@hpyer 加个微信吧，微信号：fanybook，感觉还有问题

**Comment by vipluosong** [comment]
let request = new EasyWechat.Http.Request(req, content);
req参数和content参数 应该怎么传呢？？？？版本是依赖包的版本2.11.2

**Comment by hpyer** [comment]
> let request = new EasyWechat.Http.Request(req, content); req参数和content参数 应该怎么传呢？？？？版本是依赖包的版本2.11.2

`req` 就是nodejs中请求的原始对象，比如：koa2 的 `ctx.req`
`content` 不是必须的，但是如果你的框架会自动提取请求中 body 流，就会导致本SDK无法获取的情况，这时候就可以先从框架获取到 body 内容，然后通过这个参数传给SDK来使用，可以是 object、json、xml、querystring这几种格式

可以看下[这段说明](https://github.com/hpyer/node-easywechat#%E8%AF%B7%E6%B1%82%E6%A8%A1%E5%9D%97request)

**Comment by vipluosong** [comment]
xml 我已接收到 并传入到let request = new EasyWechat.Http.Request(this.ctx.req, xml); 然后调用别的接口的时候 提示“Credential \"component_verify_ticket\" does not exist in cache.”

**Comment by hpyer** [comment]
> 

@vipluosong 稍微完整点的代码贴一下，然后收到的xml也发出来看下

这个错误就是没收到微信推送的`ComponentVerifyTicket`，SDK是会自动去缓存这个值的

**Comment by vipluosong** [comment]
<xml>
    <AppId><![CDATA[wxc5d0c9687944dde4]]></AppId>
    <Encrypt><![CDATA[lDk5vw0vO0Sakpc83w+we2i+2xsg/7t5Ddh4nmVw01wvqMHZQcPncwv0dijCVo9Ixe95/ViiaG0jvUmpj/Ltxg13Lkvq8Ml41b8zEVgAOtW9dS+Cmlx0T0omZ1plGbh71b4/F+sNEnaDllFyB6V3mkK0EVowvuEHVm348+xkzz0eepxEyYIvRek2ln1+pT6sm5e2MQ/XkSL+ICdy91yzMuQ42fvJSwvdcGBt5pb9fr7pPP9ANkCz5D6jzztTlmfiSmFkD7qjV/1ius82GQrkKPOeiD3botcl+ZMM3AICc9blgfPyf2s7pr06rP0N69o//rVYu+L7OJZot+DbzaazAoO4McOnvMBB7o6gBQvX8BuipUUpLfCCTwmnsQRvyf2EGFOhup1bzivIZEKzGX/3lJdNH9I+SKSlcOGdGahDxSdb3HucsBoaKFVX4SZAppPTHnO5wBrUY/xo2gEm+/WAOA==]]></Encrypt>
</xml>


<img width="953" alt="图片" src="https://user-images.githubusercontent.com/15122662/191170797-32e590e6-fde9-477d-986b-65d5c2c3a5ce.png">

**Comment by vipluosong** [comment]
`<xml>
    <AppId><![CDATA[wx7f17c6107d93791b]]></AppId>
    <Encrypt><![CDATA[xzWJ3nRZfL/XVNQAFKg3ow5nzSD/x9LO03n0G2Dr7ELxvcdxDQh8DdXp+7FlhRLKCuCgCHmDxzhBKBCTRXXraI/wxJFNa7VXmLE96beskWONgsMvIHC/zHCLXkSDI6HFU6q9UhggOjKAnjAlIuYPC8QNxpp6+kagwZueE+FMG3tlY/iArLIt96T4KaNF4YuocxJ7QTLV+9EIqjnjQy0RJD/ZmeaPPqjvOmilz1zlUuRUOTF0JzFjuuBJQX24KgLqmiXgRxAEzB6q53WWtljGEYh/JeMwqGvMa9i0X7POq1zefK/+/UadBZjWuJLlgbJ+/DxqQYlByVJYLgk7wrlysr908fzK7/lYB8V47WCKvi9c7+Bx8PcPv1kF/9Y3QIavU0KgFmisZUK6TJXVmndRJIdaDH+qXpPheJCzHk1rTXTGH1NjeomsI2CyAaW0CCh4tnqkMYLiihHW9qFoZY4Hlg==]]></Encrypt>
</xml>`

**Comment by hpyer** [comment]
> <img alt="图片" width="953" src="https://user-images.githubusercontent.com/15122662/191170797-32e590e6-fde9-477d-986b-65d5c2c3a5ce.png">

`callback`方法中没有执行`server.serve()`啊
这个方法会返回一个response对象，如：
```js
let app = new Easywechat.Factory.OpenPlatform({});

app.rebind('request', request);

let response = await app.server.serve();

ctx.body = response.content;
```

**Comment by vipluosong** [comment]
可以了 谢谢
