### ISSUE TITLE
Pay.uploadMedia 上传超时

### ISSUE THREAD

**Issue by ValueLan** [hpyer/node-easywechat#64]
uploadMedia 超时
以下是我魔改上传成功的例子
改动点1 如果外面设置了 authorization 就不设置 authorization
改动点2 createSignature 保护变公开

````
import { createHash } from "crypto";
import { createReadStream } from "fs";
import fs = require("fs");

 let client = this.getClient()
    let fd = new FormData();
    const buff = fs.readFileSync('./temp/zz.jpg');
    const sha256 = createHash("sha256").update(buff).digest("hex");
    fd.append('file', createReadStream('./temp/zz.jpg'), {filename: 'a.jpg'});
    let meta = { filename: 'a.jpg', sha256: sha256 }
    fd.append("meta", JSON.stringify({ filename: 'a.jpg', sha256: sha256 }), {
      contentType: 'application/json',
    })
    let res = await client.post("/v3/merchant/media/upload", {
      headers: {
        authorization: client.createSignature("post", "/v3/merchant/media/upload", {
          data: meta
        })
      },
      data: fd,
    })
````

**Comment by ValueLan** [comment]
常规上传
````
let client = this.getClient()

let res = await client.uploadMedia("https://api.mch.weixin.qq.com/v3/merchant/media/upload", './temp/zz.jpg')

\node_modules\axios\lib\core\AxiosError.js:89
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
Error: socket hang up
    at Function.AxiosError.from (\node_modules\axios\lib\core\AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (\node_modules\axios\lib\adapters\http.js:606:25)
    at RedirectableRequest.emit (node:events:525:35)
    at ClientRequest.eventHandlers.<computed> (\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketOnEnd (node:_http_client:518:9)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

````

**Comment by hpyer** [comment]
收到，今天可能没时间处理，明天再看

**Comment by ValueLan** [comment]
希望 uploadMedia 支持FormDate 类型，
如果是使用路径我需要把图片放到服务器，
如果支持FormDate 我可以直接用buffer

**Comment by hpyer** [comment]
请更新3.5.18

这个问题是因为默认将文件读取为文件流，但是文件流只能使用一次，在计算文件内容哈希的时候使用了，就导致后续上传的时候无法读取。

新版本改动：
1、默认将文件读取为buffer
2、如果传的是文件流，则转为buffer，再使用
3、支持传buffer

**Comment by ValueLan** [comment]
上传文件这个问题OK了，
其他我提交信息 含有 Wechatpay-Serial  需要加密的请求错了，报文解密失败
感觉这个你可能帮不了我，你没环境，我看看咨询下腾讯客服把
