### ISSUE TITLE
Error: Failed to decode request contents.

### ISSUE THREAD

**Issue by david-marstree** [hpyer/node-easywechat#72]
```json
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Failed to decode request contents.",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Failed to decode request contents.",
        "stack": [
            "Error: Failed to decode request contents.",
            "    at Message.<anonymous> (/var/task/node_modules/node-easywechat/dist/Core/Message.js:73:23)",
            "    at Generator.next (<anonymous>)",
            "    at /var/task/node_modules/node-easywechat/dist/Core/Message.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/var/task/node_modules/node-easywechat/dist/Core/Message.js:4:12)",
            "    at Message.createFromRequest (/var/task/node_modules/node-easywechat/dist/Core/Message.js:55:16)",
            "    at Server.getRequestMessage (/var/task/node_modules/node-easywechat/dist/OfficialAccount/Server.js:77:34)",
            "    at Server.<anonymous> (/var/task/node_modules/node-easywechat/dist/OfficialAccount/Server.js:33:38)",
            "    at Generator.next (<anonymous>)",
            "    at /var/task/node_modules/node-easywechat/dist/OfficialAccount/Server.js:8:71"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Failed to decode request contents.",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)",
        "    at process.emit (node:events:517:28)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

my code is here
```typescript

import express from "express";
import bodyParser from "body-parser";
import awsServerlessExpressMiddleware from "aws-serverless-express/middleware";
import {
  OfficialAccount,
  ServerRequest,
  defineOfficialAccountConfig,
} from "node-easywechat";

const config = defineOfficialAccountConfig({
  app_id: "wx1d5a2dfe696b5927",
  secret: "xxxxxx",
  token: "xxxxxx",
  aes_key: "xxxxx",
});

const app = express();
app.use(bodyParser.json());
app.use(awsServerlessExpressMiddleware.eventContext());

// Enable CORS for all methods
app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "*");
  next();
});

app.get("/server", async (req, res) => {
  // Add your code here
  const wechatApp = new OfficialAccount(config);

  let request = await ServerRequest.createFromIncomingMessage(req);
  wechatApp.setRequest(request);

  const client = wechatApp.getClient();
  client.setLogger((type, options, useTime, response) => {
    if (type === "after") {
      console.log(type, response?.config, useTime, response?.data);
    } else {
      console.log(type, options, options.data instanceof FormData);
    }
  });

  let server = wechatApp.getServer();
  server.with(async (message) => {
    console.log("receive message", message);
    return "success";
  });
  let response = await server.serve();
  // console.log("response", response);

  res.set("Content-Type", response.getHeader("content-type"));
  res.send(response.getBody());
});

app.listen(3000, () => {
  console.log("App started");
});

export default app;

```

**Comment by hpyer** [comment]
I test your code, and found one error.

`app.get("/server", ()=>{})` here should use `app.all()` to handle both `get` and `post` request.

NOTICE:
The real messages are send with POST method, looks like below:

```
URL:
http://example.com/server?signature=xxx&timestamp=xxx&nonce=xxx&openid=xxx&encrypt_type=aes&msg_signature=xxx

BODY:
<xml>
<ToUserName>xxx</ToUserName>
<Encrypt>xxx</Encrypt>
</xml>
```

**Comment by david-marstree** [comment]
Yes, I try it. however, it is also error.
It seem that getServer() cannot be run. 
```
  let server = wechatApp.getServer();
```

**Comment by hpyer** [comment]
I tried your code, it's run successful for me.

You can debug your code again, and try print the body of `request`.

```js
let request = await ServerRequest.createFromIncomingMessage(req);
wechatApp.setRequest(request);
console.log('reques_body', request.getBody().toString());
```

You shold set the second parameter of `ServerRequest.createFromIncomingMessage`, if the body is empty or neither XML and JSON.

Like this:

```js
// make sure req.body has value
let request = await ServerRequest.createFromIncomingMessage(req, req.body);
wechatApp.setRequest(request);
```
