### ISSUE TITLE
【功能请求】请求添加视频号小店接口

### ISSUE THREAD

**Issue by absir1949** [hpyer/node-easywechat#77]
RT

**Comment by hpyer** [comment]
收到～回头我找下文档，抽空加一下。如果你有空，也欢迎提PR～

**Comment by absir1949** [comment]
> 收到～回头我找下文档，抽空加一下。如果你有空，也欢迎提PR～

主要是不太熟悉 T_T

**Comment by hpyer** [comment]
看了视频号小店的文档，对于AccessToken的获取跟公众号是一样的。所以如果急的话，完全可以套用公众号的方式先使用，代码类似：

```js
const { OfficialAccount } = require('node-easywechat');
// 实例化应用
const app = new OfficialAccount({
  app_id: '', // 视频号小店的appid
  secret: '',
  token: '',
  aes_key: '',
});

// 获取 api 调用客户端
const client = app.getClient();
// 请求 api
// 注意，这里返回的是 HttpClientResponse 对象
const response = await client.post('/channels/ec/order/list/get', {
    create_time_range: {
        start_time: 1658505600,
        end_time: 1658509200
    },
    page_size: 20,
});
// 获取具体数据
let data = response.toObject();
```

**Comment by hpyer** [comment]
刚发布了 `3.7.0` 版本，新增了 `视频号` 模块。示例代码如下：

```js
const { Channel } = require('node-easywechat');
// 实例化应用
const app = new Channel({
  app_id: '',
  secret: '',
  token: '',
  aes_key: '',
});

// 获取 api 调用客户端
const client = app.getClient();
// 请求 api
// 注意，这里返回的是 HttpClientResponse 对象
const response = await client.post('/channels/ec/order/list/get', {
    create_time_range: {
        start_time: 1658505600,
        end_time: 1658509200
    },
    page_size: 20,
});
// 获取具体数据
let data = response.toObject();
```

**Comment by absir1949** [comment]
@hpyer  这个可以,但视频号请求回调貌似存在问题
```const express = require('express');
const { Channel,ServerRequest } = require('node-easywechat');
const bodyParser = require('body-parser');

const app = express();
app.use(bodyParser.text({ type: 'text/xml' }));



// 实例化应用
const wechatApp = new Channel({
  app_id: '',
  secret: '',
  token: '',
  aes_key: '',
});


  
  // 消息回调处理接口
app.get('/wechat/callback', (req, res) => {
    const request = ServerRequest.createFromIncomingMessage(req);
    wechatApp.setRequest(request);
    const server = wechatApp.getServer();
    server.addEventListener('channels_ec_order_new', (message, req, res) => {
        console.log('Order created:', message);
        res.reply('success');
    });

    server.addEventListener('channels_ec_order_cancel', (message, req, res) => {
        console.log('Order canceled:', message);
        res.reply('success');
    });

    server.serve(req, res); 
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
console.log(`Server is running on port ${port}`);
});```


报错

```(node:2434570) UnhandledPromiseRejectionWarning: TypeError: this.request.getQueryParams is not a function
    at Server.<anonymous> (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/OfficialAccount/Server.js:29:40)
    at Generator.next (<anonymous>)
    at /root/code/wxchannel-shop/node_modules/node-easywechat/dist/OfficialAccount/Server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/OfficialAccount/Server.js:4:12)
    at Server.serve (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/OfficialAccount/Server.js:28:16)
    at /root/code/wxchannel-shop/test/callback-test.js:35:12
    at Layer.handle [as handle_request] (/root/code/wxchannel-shop/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/code/wxchannel-shop/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/root/code/wxchannel-shop/node_modules/express/lib/router/route.js:119:3)```

**Comment by hpyer** [comment]
收到，晚点排查一下

**Comment by hpyer** [comment]
几个问题。

1.  服务端应该响应 `get` 和 `post` 两种请求方式，所以就用 `all` 来处理路由；
2. `ServerRequest.createFromIncomingMessage` 和 `server.serve` 都是异步的，包括 `addEventListener` 方法传入的闭包也是异步的。
3. `express ` 输出响应结果用的是 `res.send` 方法；

正确代码如下：

```js
// 消息回调处理接口
app.all('/wechat/callback', async (req, res) => {
  const request = await ServerRequest.createFromIncomingMessage(req);
  wechatApp.setRequest(request);
  const server = wechatApp.getServer();
  server.addEventListener('channels_ec_order_new', (message) => {
    console.log('Order created:', message);
  });

  server.addEventListener('channels_ec_order_cancel', (message) => {
    console.log('Order canceled:', message);
  });

  const response = await server.serve();

  res.send(response.getBody());
});
```

**Comment by absir1949** [comment]
@hpyer 
感谢,上面可以,再请教下,如果在addEventListener 里面回复 scuess,应该怎么写呢?
`
  server.addEventListener('channels_ec_order_new', async(message) => {
    console.log('Order created:', message);
    res.reply('success');
  });
`
这样写感觉不对
(node:3318423) UnhandledPromiseRejectionWarning: Error: Invalid request signature.

**Comment by hpyer** [comment]
在消息处理的闭包函数里直接`return`或者`return true`就可以，默认就是自动输出success

**Comment by absir1949** [comment]
@hpyer 大佬,不行啊
`
  server.addEventListener('channels_ec_order_new', (message, req, res) => {
    console.log('Order created:', message);
    return true;
  });
`
(node:3343922) UnhandledPromiseRejectionWarning: Error: Invalid request signature.
    at Server.validateSignature (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/Core/Mixins/DecryptMessageMixin.js:40:19)
    at Server.<anonymous> (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/Core/Mixins/DecryptMessageMixin.js:20:18)

**Comment by hpyer** [comment]
你看下错误原因，`Invalid request signature` 这是签名错误。你查下你的配置项是不是跟视频号后台设置的一样的。

下面是我根据 [官方文档](https://developers.weixin.qq.com/doc/channels/API/basics/message_push.html) 写的测试代码，消息解密是没问题的。

```js
const { Channel, ServerRequest } = require('node-easywechat');
const express = require('express');
const bodyParser = require('body-parser');

const app = express();
app.use(bodyParser.text({ type: 'text/xml' }));

// 实例化应用
const wechatApp = new Channel({
  app_id: 'wxba5fad812f8e6fb9',
  secret: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  token: 'AAAAA',
  aes_key: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
});

// 消息回调处理接口
app.all('/wechat/callback', async (req, res) => {
  const request = await ServerRequest.createFromIncomingMessage(req);
  wechatApp.setRequest(request);
  const server = wechatApp.getServer();

  server.with(async (message) => {
    console.log('Message:', message);
    return true;
  });

  const response = await server.serve();

  res.send(response.getBody());
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
```

请求方式：`POST`

请求地址：`http://127.0.0.1:3000/wechat/callback?signature=6c5c811b55cc85e0e1b54100749188c20beb3f5d&timestamp=1714112445&nonce=415670741&openid=o9AgO5Kd5ggOC-bXrbNODIiE3bGY&encrypt_type=aes&msg_signature=046e02f8204d34f8ba5fa3b1db94908f3df2e9b3`

请求内容：
```json
{
    "ToUserName": "gh_97417a04a28d",
    "Encrypt": "+qdx1OKCy+5JPCBFWw70tm0fJGb2Jmeia4FCB7kao+/Q5c/ohsOzQHi8khUOb05JCpj0JB4RvQMkUyus8TPxLKJGQqcvZqzDpVzazhZv6JsXUnnR8XGT740XgXZUXQ7vJVnAG+tE8NUd4yFyjPy7GgiaviNrlCTj+l5kdfMuFUPpRSrfMZuMcp3Fn2Pede2IuQrKEYwKSqFIZoNqJ4M8EajAsjLY2km32IIjdf8YL/P50F7mStwntrA2cPDrM1kb6mOcfBgRtWygb3VIYnSeOBrebufAlr7F9mFUPAJGj04="
}
```

**Comment by absir1949** [comment]
@hpyer 
还真不是,确认配置项是没错的,这个解密数据能拿到
但是还是报错
```
Message: Message {
  originContent: '{"ToUserName":"gh_4e453950c446","Encrypt":"oM83RoYG37JS4Wjz3bLr6nN36jApSMDKjPLF2XgKFEu9wpHHDlvyk/u5Or0w5XSX9qdFWYjAAiy9gNJZtzlsX4x0nZDO5UXlqlTBJ/OOW/wqXOsT0YDwrIO6D1OlnLbUTH3usk8LKyIdYdmBDmBEVar6x/t2KslZ/UdYU4GtCp4AhXzSDJ9A8WqOcnIdcYccffr9eGEpGbFgJUDp2zVwyvosFwrdhYKYUm9kkg9AgWcchm5feUNgR+j156QZRFQDJ45sMMX6ZrLm/YBxf1ggcve3eNxl5Rtv3XNLFIGJj7cnLCz38fuCLZUYchWHGUgNFMY7h1hnVpkzTLHRG5OEw7UT7SVoQzcxa2KUclglJeH0B7zQ+OdCxBYSFlnlicFi"}',
  attributes: {
    ToUserName: 'gh_4e453950c446',
    Encrypt: 'oM83RoYG37JS4Wjz3bLr6nN36jApSMDKjPLF2XgKFEu9wpHHDlvyk/u5Or0w5XSX9qdFWYjAAiy9gNJZtzlsX4x0nZDO5UXlqlTBJ/OOW/wqXOsT0YDwrIO6D1OlnLbUTH3usk8LKyIdYdmBDmBEVar6x/t2KslZ/UdYU4GtCp4AhXzSDJ9A8WqOcnIdcYccffr9eGEpGbFgJUDp2zVwyvosFwrdhYKYUm9kkg9AgWcchm5feUNgR+j156QZRFQDJ45sMMX6ZrLm/YBxf1ggcve3eNxl5Rtv3XNLFIGJj7cnLCz38fuCLZUYchWHGUgNFMY7h1hnVpkzTLHRG5OEw7UT7SVoQzcxa2KUclglJeH0B7zQ+OdCxBYSFlnlicFi',
    FromUserName: 'o9jwn41OXOL-ILbBb7hLTvBCKsEw',
    CreateTime: 1716365208,
    MsgType: 'event',
    Event: 'product_order_status_update',
    ProductOrderStatusUpdate: { order_id: 3720021270198095000, status: 250 }
  }
}
(node:3911744) UnhandledPromiseRejectionWarning: Error: Invalid request signature.
    at Server.validateSignature (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/Core/Mixins/DecryptMessageMixin.js:40:19)
    at Server.<anonymous> (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/Core/Mixins/DecryptMessageMixin.js:20:18)
    at Generator.next (<anonymous>)
    at /root/code/wxchannel-shop/node_modules/node-easywechat/dist/Core/Mixins/DecryptMessageMixin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/Core/Mixins/DecryptMessageMixin.js:4:12)
    at Server.decryptMessage (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/Core/Mixins/DecryptMessageMixin.js:18:16)
    at Server.<anonymous> (/root/code/wxchannel-shop/node_modules/node-easywechat/dist/OfficialAccount/Server.js:86:24)
    at Generator.next (<anonymous>)
    at /root/code/wxchannel-shop/node_modules/node-easywechat/dist/OfficialAccount/Server.js:8:71
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by hpyer** [comment]
你用我示例里的配置项，写个简单的能复现这个问题的项目，我跑下看。我这里是复现不出来你的问题。

**Comment by absir1949** [comment]
我就是用你的测试代码,就能复现这个问题
(node:1045525) UnhandledPromiseRejectionWarning: Error: Invalid request signature.

**Comment by hpyer** [comment]
………那你倒是把你的开发环境，依赖包版本什么的尽量都写一下呀，不然我怎么复现。你寻求帮助，还要我一个个问题问你吗？那你到底是想要人帮还是不想要人帮呢？

我这里是16，18，20，22的几个最新版本都试过了没问题的。
